# Generated by Django 5.2 on 2025-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('twin_call_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
