# Generated by Django 5.2 on 2025-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='twin_call_id',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
